import { NextResponse } from 'next/server';
import { createLeadAndAssign } from '@/services/lead-service';
import { concurrentLeadSchema } from '@/lib/validation';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

export async function POST(request: Request) {
  const body = await request.json().catch(() => null);
  const parsed = concurrentLeadSchema.safeParse(body);

  if (!parsed.success) {
    return NextResponse.json(
      {
        error: 'Invalid concurrent lead payload.',
        issues: parsed.error.flatten()
      },
      { status: 400 }
    );
  }

  const timestamp = Date.now();
  const jobs = Array.from({ length: parsed.data.count }, (_, index) =>
    createLeadAndAssign({
      serviceId: parsed.data.serviceId,
      name: `Concurrent Lead ${index + 1}`,
      phone: `${timestamp}${index}`,
      city: 'Test City',
      description: 'Generated by test tools'
    })
  );

  const results = await Promise.allSettled(jobs);
  const successCount = results.filter((result) => result.status === 'fulfilled').length;
  const failureCount = results.length - successCount;

  return NextResponse.json({
    message: `Concurrent lead generation finished: ${successCount} succeeded, ${failureCount} failed.`,
    successCount,
    failureCount,
    results: results.map((result) =>
      result.status === 'fulfilled'
        ? {
            ok: true,
            leadId: result.value.lead.id,
            assigned: result.value.assigned
          }
        : {
            ok: false,
            error: result.reason instanceof Error ? result.reason.message : 'Unknown error'
          }
    )
  });
}
